{{ config(schema='gold', materialized='table') }}

SELECT surrogate_merge_key,
        weather_model,
        cycle_date,
        cycle_hour,
        forecast_step_hours,
        valid_date,
        valid_hour,
        lat,
        lon,
        lat_i,
        lon_i,
        pressure_level_hpa,
        temp_spread_kelvin,
        temp_spread_celsius,
        geopotential_height_spread_m,
        dbt_updated_at FROM {{ ref('fct_aifs_spread') }}
UNION ALL
SELECT surrogate_merge_key,
    weather_model,
    cycle_date,
    cycle_hour,
    forecast_step_hours,
    valid_date,
    valid_hour,
    lat,
    lon,
    lat_i,
    lon_i,

    pressure_level_hpa,
    temp_spread_kelvin,
    temp_spread_celsius,
    geopotential_height_spread_m,
    dbt_updated_at FROM {{ ref('fct_ifs_spread') }}