# Dockerfile.dbt_snowflake
FROM python:3.12.3-slim

# Custom image for running dbt commands
# FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    git \
    gcc \
    # Snowflake adapter dependencies
    libssl-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# install Snowflake adapter for dbt, pinned to 1.8.0 which is the latest series available in PyPI
RUN pip install --no-cache-dir "dbt-snowflake==1.8.0"

WORKDIR /usr/app
ENTRYPOINT ["bash"]