# profiles.yml
physical_meteor:
  target: dev
  outputs:
    # Local engine for real-time ground signals (Freeze Line / 850mb)
    dev:
      type: postgres
      host: postgres #host.docker.internal
      user: airflow
      password: {{ env_var('POSTGRES_PASS') }}
      port: 5432
      dbname: PHYSICAL_METEOR_DB  # Target our meteorology DB
      schema: RAW                 # Load seeds into the RAW schema      threads: 4
      keepalives_idle: 0

    # Cloud engine for massive historical re-analysis (500mb / Jet / EPO)
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False